language: python

python:
  - "3.6"
addons:
  firefox: "55.0"

install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz -O geckodriver.tar.gz
  - mkdir geckodriver
  - tar -xzf ./geckodriver.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - pip install -r remote/requirements.txt pytest-cov coveralls

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

script:
  pytest --cov ./test/remote/

after_success:
  - coveralls
